name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - setting_CI
  pull_request:
    branches:
      - main
      - develop
      - setting_CI
 
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras
          
      - name: Run Ruff
        run: uv run ruff check .
    continue-on-error: True
          
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          
      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest -v
          uv run coverage report --fail-under=90
